### ISSUE TITLE
ABOUT LOAD BALANCER 

### ISSUE THREAD

**Issue by Arpit529Srivastava** [ThanhCorn/all-about-go#2]
I wanted to add a [Load Balancer](https://aws.amazon.com/what-is/load-balancing/) in [Round Robin Algorithm](https://avinetworks.com/glossary/round-robin-load-balancing/)

Diagram about a Load Balancer in Round Robin Algorithm
![round_robin](https://github.com/user-attachments/assets/3f74ad5b-6e20-4a3d-8f86-4565706e6393)

@ThanhCorn please review this and add this as label hacktoberfest

**Comment by Rizz-33** [comment]
the attached asset is not accessible ig. 

@Arpit529Srivastava
